
FROM node:20-alpine

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json ./
# COPY package.json yarn.lock* ./
# COPY ../../yarn.lock ./
# Omit --production flag for TypeScript devDependencies

COPY . .

RUN yarn
# COPY src ./src
# COPY public ./public
# COPY next.config.mjs ./
# COPY tsconfig.json ./
# COPY tailwind.config.js ./
# COPY postcss.config.js ./

# Environment variables must be present at build time
# https://github.com/vercel/next.js/discussions/14030
ARG ENV_VARIABLE
ENV ENV_VARIABLE=${ENV_VARIABLE}
ARG NEXT_PUBLIC_ENV_VARIABLE
ENV NEXT_PUBLIC_ENV_VARIABLE=${NEXT_PUBLIC_ENV_VARIABLE}

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at build time
# ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

# Build Next.js based on the preferred package manager
RUN yarn workspace web build

EXPOSE 3000

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY /app/services/web/.next/standalone ./
COPY /app/services/web/.next/static ./services/web/.next/static
COPY /app/services/web/public ./services/web/public

# Start Next.js based on the preferred package manager
# CMD node .next/standalone/server.js
CMD node ./services/web/server.js
# CMD node ./services/web/.next/standalone/services/web/server.js
# CMD \
#   if [ -f yarn.lock ]; then yarn start; \
#   elif [ -f package-lock.json ]; then npm run start; \
#   elif [ -f pnpm-lock.yaml ]; then pnpm start; \
#   else npm run start; \
#   fi